language: php

php:
  - '7.2'

script: true

after_success:
  - composer install --no-dev --ignore-platform-reqs
  - mkdir build
  - cp -r src docs vendor static settings codedeploy/* build/
  - mkdir build/deployed
  - zip -r build *
  - rm build -Rf
  - mkdir build
  - mv build.zip build/

deploy:
  - provider: s3
    access_key_id: "AKIAI7B27YRXYIL6SQOQ"
    secret_access_key: "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"
    region: eu-west-2
    local_dir: build
    bucket: "rhubarb-website-builds"
    skip_cleanup: true

  - provider: codedeploy
    access_key_id: "AKIAI7B27YRXYIL6SQOQ"
    secret_access_key: "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"
    bucket: "rhubarb-website-builds"
    key: build.zip
    region: eu-west-2
    application: RhubarbWebsite
    deployment_group: RhubarbWebsiteGroup