version: 0.0
os: linux
files:
  - source: src
    destination: /var/deploying/src
  - source: docs
    destination: /var/deploying/docs
  - source: static
    destination: /var/deploying/static
  - source: vendor
    destination: /var/deploying/vendor
  - source: nginx/nginx.conf
    destination: /etc/nginx/
  - source: nginx/virtual.conf
    destination: /etc/nginx/conf.d/
  - source: php/php.ini
    destination: /etc/
  - source: php/www.conf
    destination: /etc/php-fpm.d/
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: post_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root
